/* Generated By:JavaCC: Do not edit this line. PerfParserConstants.java */
package perfcenter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PerfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SCENARIO = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int DEVICE = 10;
  /** RegularExpression Id. */
  int CPU = 11;
  /** RegularExpression Id. */
  int IO = 12;
  /** RegularExpression Id. */
  int PS = 13;
  /** RegularExpression Id. */
  int FCFS = 14;
  /** RegularExpression Id. */
  int LCFS = 15;
  /** RegularExpression Id. */
  int XCS = 16;
  /** RegularExpression Id. */
  int DEPLOY = 17;
  /** RegularExpression Id. */
  int UNDEPLOY = 18;
  /** RegularExpression Id. */
  int HOST = 19;
  /** RegularExpression Id. */
  int SERVER = 20;
  /** RegularExpression Id. */
  int COUNT = 21;
  /** RegularExpression Id. */
  int PROB = 22;
  /** RegularExpression Id. */
  int SYNC = 23;
  /** RegularExpression Id. */
  int SERVT = 24;
  /** RegularExpression Id. */
  int AT = 25;
  /** RegularExpression Id. */
  int THREAD = 26;
  /** RegularExpression Id. */
  int TASK = 27;
  /** RegularExpression Id. */
  int BUFFER = 28;
  /** RegularExpression Id. */
  int SOFTRES = 29;
  /** RegularExpression Id. */
  int SCHEDP = 30;
  /** RegularExpression Id. */
  int SPEEDUP = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int FALSE = 33;
  /** RegularExpression Id. */
  int RAM = 34;
  /** RegularExpression Id. */
  int STATICSIZE = 35;
  /** RegularExpression Id. */
  int REQUESTSIZE = 36;
  /** RegularExpression Id. */
  int SIZE = 37;
  /** RegularExpression Id. */
  int WARNINGS = 38;
  /** RegularExpression Id. */
  int POWERMANAGED = 39;
  /** RegularExpression Id. */
  int GOVERNOR = 40;
  /** RegularExpression Id. */
  int CONSERVATIVE = 41;
  /** RegularExpression Id. */
  int ONDEMAND = 42;
  /** RegularExpression Id. */
  int PERFORMANCE = 43;
  /** RegularExpression Id. */
  int POWERSAVE = 44;
  /** RegularExpression Id. */
  int USERSPACE = 45;
  /** RegularExpression Id. */
  int POWERMANAGEMENT = 46;
  /** RegularExpression Id. */
  int SPEEDLEVELS = 47;
  /** RegularExpression Id. */
  int POWERCONSUMEDLEVELS = 48;
  /** RegularExpression Id. */
  int IDLEPOWER = 49;
  /** RegularExpression Id. */
  int SETSPEEDLEVELINDEX = 50;
  /** RegularExpression Id. */
  int PROBEINTERVAL = 51;
  /** RegularExpression Id. */
  int PROBEINTERVALDOWNFACTOR = 52;
  /** RegularExpression Id. */
  int GOVERNOR_UP_THRESHOLD = 53;
  /** RegularExpression Id. */
  int GOVERNOR_DOWN_THRESHOLD = 54;
  /** RegularExpression Id. */
  int LAN = 55;
  /** RegularExpression Id. */
  int LINK = 56;
  /** RegularExpression Id. */
  int PROP = 57;
  /** RegularExpression Id. */
  int TRANS = 58;
  /** RegularExpression Id. */
  int HEADERSIZE = 59;
  /** RegularExpression Id. */
  int BYTES = 60;
  /** RegularExpression Id. */
  int MS = 61;
  /** RegularExpression Id. */
  int US = 62;
  /** RegularExpression Id. */
  int NS = 63;
  /** RegularExpression Id. */
  int KBPS = 64;
  /** RegularExpression Id. */
  int BPS = 65;
  /** RegularExpression Id. */
  int MBPS = 66;
  /** RegularExpression Id. */
  int GBPS = 67;
  /** RegularExpression Id. */
  int MTU = 68;
  /** RegularExpression Id. */
  int EXP = 69;
  /** RegularExpression Id. */
  int NOR = 70;
  /** RegularExpression Id. */
  int POI = 71;
  /** RegularExpression Id. */
  int UNI = 72;
  /** RegularExpression Id. */
  int BETA = 73;
  /** RegularExpression Id. */
  int BINOM = 74;
  /** RegularExpression Id. */
  int CHISQR = 75;
  /** RegularExpression Id. */
  int GAMMA = 76;
  /** RegularExpression Id. */
  int CONST = 77;
  /** RegularExpression Id. */
  int RESPT = 78;
  /** RegularExpression Id. */
  int WAITT = 79;
  /** RegularExpression Id. */
  int UTIL = 80;
  /** RegularExpression Id. */
  int QLEN = 81;
  /** RegularExpression Id. */
  int POWER = 82;
  /** RegularExpression Id. */
  int EPERR = 83;
  /** RegularExpression Id. */
  int PDP = 84;
  /** RegularExpression Id. */
  int PEFF = 85;
  /** RegularExpression Id. */
  int TPUT = 86;
  /** RegularExpression Id. */
  int BPUT = 87;
  /** RegularExpression Id. */
  int GPUT = 88;
  /** RegularExpression Id. */
  int BUFFTIMEOUT = 89;
  /** RegularExpression Id. */
  int DROPRATE = 90;
  /** RegularExpression Id. */
  int AVGSERVT = 91;
  /** RegularExpression Id. */
  int QPARMS = 92;
  /** RegularExpression Id. */
  int BOTTLENECK = 93;
  /** RegularExpression Id. */
  int BLOCKPROB = 94;
  /** RegularExpression Id. */
  int PRINTCFG = 95;
  /** RegularExpression Id. */
  int ARATE = 96;
  /** RegularExpression Id. */
  int ANALYSE = 97;
  /** RegularExpression Id. */
  int INTERVAL = 98;
  /** RegularExpression Id. */
  int FREQ = 99;
  /** RegularExpression Id. */
  int FOREACH = 100;
  /** RegularExpression Id. */
  int FOR = 101;
  /** RegularExpression Id. */
  int TO = 102;
  /** RegularExpression Id. */
  int INCR = 103;
  /** RegularExpression Id. */
  int DECR = 104;
  /** RegularExpression Id. */
  int SET = 105;
  /** RegularExpression Id. */
  int PRINT = 106;
  /** RegularExpression Id. */
  int IN = 107;
  /** RegularExpression Id. */
  int AND = 108;
  /** RegularExpression Id. */
  int IF = 109;
  /** RegularExpression Id. */
  int THEN = 110;
  /** RegularExpression Id. */
  int ELSE = 111;
  /** RegularExpression Id. */
  int WHILE = 112;
  /** RegularExpression Id. */
  int BREAK = 113;
  /** RegularExpression Id. */
  int BRANCH = 114;
  /** RegularExpression Id. */
  int MODELPARAMS = 115;
  /** RegularExpression Id. */
  int LOADPARAMS = 116;
  /** RegularExpression Id. */
  int ANALYTICAL = 117;
  /** RegularExpression Id. */
  int SIMULATION = 118;
  /** RegularExpression Id. */
  int THINKTIME = 119;
  /** RegularExpression Id. */
  int TIMEOUT = 120;
  /** RegularExpression Id. */
  int RETRYPROB = 121;
  /** RegularExpression Id. */
  int OPEN = 122;
  /** RegularExpression Id. */
  int TYPE = 123;
  /** RegularExpression Id. */
  int METHOD = 124;
  /** RegularExpression Id. */
  int CLOSED = 125;
  /** RegularExpression Id. */
  int NOOFUSERS = 126;
  /** RegularExpression Id. */
  int NOOFREQUESTS = 127;
  /** RegularExpression Id. */
  int SIMENDTIME = 128;
  /** RegularExpression Id. */
  int CONFINT = 129;
  /** RegularExpression Id. */
  int REPLICATIONNO = 130;
  /** RegularExpression Id. */
  int STARTUPSAMPLENO = 131;
  /** RegularExpression Id. */
  int OUTPUT = 132;
  /** RegularExpression Id. */
  int COOLDOWNSAMPLENO = 133;
  /** RegularExpression Id. */
  int ENABLE = 134;
  /** RegularExpression Id. */
  int DISABLE = 135;
  /** RegularExpression Id. */
  int MAXRETRY = 136;
  /** RegularExpression Id. */
  int WORKLOAD = 137;
  /** RegularExpression Id. */
  int CYCLIC = 138;
  /** RegularExpression Id. */
  int CONSTANT = 139;
  /** RegularExpression Id. */
  int NUMBER = 140;
  /** RegularExpression Id. */
  int STRING_LITERAL = 141;
  /** RegularExpression Id. */
  int FILENAME = 142;
  /** RegularExpression Id. */
  int IDENTIFIER = 143;
  /** RegularExpression Id. */
  int DIGITS = 144;
  /** RegularExpression Id. */
  int LETTER = 145;
  /** RegularExpression Id. */
  int DIGIT = 146;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"scenario\"",
    "\"end\"",
    "\"variable\"",
    "\"device\"",
    "\"cpu\"",
    "\"io\"",
    "\"ps\"",
    "\"fcfs\"",
    "\"lcfs\"",
    "\"xcs\"",
    "\"deploy\"",
    "\"undeploy\"",
    "\"host\"",
    "\"server\"",
    "\"count\"",
    "\"prob\"",
    "\"sync\"",
    "\"servt\"",
    "\"at\"",
    "\"thread\"",
    "\"task\"",
    "\"buffer\"",
    "\"softres\"",
    "\"schedp\"",
    "\"speedup\"",
    "\"true\"",
    "\"false\"",
    "\"ram\"",
    "\"staticsize\"",
    "\"requestsize\"",
    "\"size\"",
    "\"warnings\"",
    "\"power_managed\"",
    "\"governor\"",
    "\"conservative\"",
    "\"ondemand\"",
    "\"performance\"",
    "\"powersave\"",
    "\"userspace\"",
    "\"powermanagement\"",
    "\"speed_levels\"",
    "\"power_consumed\"",
    "\"idlepower\"",
    "\"setspeed_level_index\"",
    "\"probe_interval\"",
    "\"probe_interval_down_factor\"",
    "\"governor_up_threshold\"",
    "\"governor_down_threshold\"",
    "\"lan\"",
    "\"link\"",
    "\"prop\"",
    "\"trans\"",
    "\"headersize\"",
    "\"bytes\"",
    "\"ms\"",
    "\"us\"",
    "\"ns\"",
    "\"Kbps\"",
    "\"bps\"",
    "\"Mbps\"",
    "\"Gbps\"",
    "\"mtu\"",
    "\"exp\"",
    "\"nor\"",
    "\"poi\"",
    "\"uni\"",
    "\"beta\"",
    "\"binom\"",
    "\"chisqr\"",
    "\"gamma\"",
    "\"const\"",
    "\"respt\"",
    "\"waitt\"",
    "\"util\"",
    "\"qlen\"",
    "\"power\"",
    "\"eperr\"",
    "\"pdp\"",
    "\"peff\"",
    "\"tput\"",
    "\"bput\"",
    "\"gput\"",
    "\"buffTimeout\"",
    "\"droprate\"",
    "\"avgservt\"",
    "\"qparms\"",
    "\"bottleneck\"",
    "\"blockprob\"",
    "\"printcfg\"",
    "\"arate\"",
    "\"analyse\"",
    "\"interval\"",
    "\"freq\"",
    "\"foreach\"",
    "\"for\"",
    "\"to\"",
    "\"incr\"",
    "\"decr\"",
    "\"set\"",
    "\"print\"",
    "\"in\"",
    "\"and\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"break\"",
    "\"branch\"",
    "\"modelparams\"",
    "\"loadparams\"",
    "\"analytical\"",
    "\"simulation\"",
    "\"thinktime\"",
    "\"timeout\"",
    "\"retryProb\"",
    "\"open\"",
    "\"type\"",
    "\"method\"",
    "\"closed\"",
    "\"noofusers\"",
    "\"noofrequests\"",
    "\"simendtime\"",
    "\"confint\"",
    "\"replicationno\"",
    "\"startupsampleno\"",
    "\"output\"",
    "\"cooldownsampleno\"",
    "\"enable\"",
    "\"disable\"",
    "\"maxretry\"",
    "\"workload\"",
    "\"cyclic\"",
    "\"constant\"",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "<FILENAME>",
    "<IDENTIFIER>",
    "<DIGITS>",
    "<LETTER>",
    "<DIGIT>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\":\"",
    "\"()\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
