/* Generated By:JavaCC: Do not edit this line. PerfParserConstants.java */
package perfcenter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PerfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SCENARIO = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int PDEVICE = 10;
  /** RegularExpression Id. */
  int DEVICECATEGORY = 11;
  /** RegularExpression Id. */
  int VDEVICE = 12;
  /** RegularExpression Id. */
  int CPU = 13;
  /** RegularExpression Id. */
  int NONCPU = 14;
  /** RegularExpression Id. */
  int VCPU = 15;
  /** RegularExpression Id. */
  int VSTORAGE = 16;
  /** RegularExpression Id. */
  int PS = 17;
  /** RegularExpression Id. */
  int FCFS = 18;
  /** RegularExpression Id. */
  int LCFS = 19;
  /** RegularExpression Id. */
  int XCS = 20;
  /** RegularExpression Id. */
  int DEPLOY = 21;
  /** RegularExpression Id. */
  int UNDEPLOY = 22;
  /** RegularExpression Id. */
  int PHYSICALMACHINE = 23;
  /** RegularExpression Id. */
  int VIRTUALMACHINE = 24;
  /** RegularExpression Id. */
  int SERVER = 25;
  /** RegularExpression Id. */
  int COUNT = 26;
  /** RegularExpression Id. */
  int PROB = 27;
  /** RegularExpression Id. */
  int SYNC = 28;
  /** RegularExpression Id. */
  int SERVT = 29;
  /** RegularExpression Id. */
  int AT = 30;
  /** RegularExpression Id. */
  int THREAD = 31;
  /** RegularExpression Id. */
  int TASK = 32;
  /** RegularExpression Id. */
  int BUFFER = 33;
  /** RegularExpression Id. */
  int BASESPEED = 34;
  /** RegularExpression Id. */
  int SOFTRES = 35;
  /** RegularExpression Id. */
  int SCHEDP = 36;
  /** RegularExpression Id. */
  int SPEEDUP = 37;
  /** RegularExpression Id. */
  int TRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int RAM = 40;
  /** RegularExpression Id. */
  int STATICSIZE = 41;
  /** RegularExpression Id. */
  int SIZE = 42;
  /** RegularExpression Id. */
  int WARNINGS = 43;
  /** RegularExpression Id. */
  int POWERMANAGED = 44;
  /** RegularExpression Id. */
  int GOVERNOR = 45;
  /** RegularExpression Id. */
  int CONSERVATIVE = 46;
  /** RegularExpression Id. */
  int ONDEMAND = 47;
  /** RegularExpression Id. */
  int PERFORMANCE = 48;
  /** RegularExpression Id. */
  int POWERSAVE = 49;
  /** RegularExpression Id. */
  int USERSPACE = 50;
  /** RegularExpression Id. */
  int POWERMANAGEMENT = 51;
  /** RegularExpression Id. */
  int SPEEDLEVELS = 52;
  /** RegularExpression Id. */
  int POWERCONSUMEDLEVELS = 53;
  /** RegularExpression Id. */
  int IDLEPOWER = 54;
  /** RegularExpression Id. */
  int SETSPEEDLEVELINDEX = 55;
  /** RegularExpression Id. */
  int PROBEINTERVAL = 56;
  /** RegularExpression Id. */
  int PROBEINTERVALDOWNFACTOR = 57;
  /** RegularExpression Id. */
  int GOVERNOR_UP_THRESHOLD = 58;
  /** RegularExpression Id. */
  int GOVERNOR_DOWN_THRESHOLD = 59;
  /** RegularExpression Id. */
  int LAN = 60;
  /** RegularExpression Id. */
  int LINK = 61;
  /** RegularExpression Id. */
  int PROP = 62;
  /** RegularExpression Id. */
  int TRANS = 63;
  /** RegularExpression Id. */
  int HEADERSIZE = 64;
  /** RegularExpression Id. */
  int BYTES = 65;
  /** RegularExpression Id. */
  int MS = 66;
  /** RegularExpression Id. */
  int US = 67;
  /** RegularExpression Id. */
  int NS = 68;
  /** RegularExpression Id. */
  int KBPS = 69;
  /** RegularExpression Id. */
  int BPS = 70;
  /** RegularExpression Id. */
  int MBPS = 71;
  /** RegularExpression Id. */
  int GBPS = 72;
  /** RegularExpression Id. */
  int MTU = 73;
  /** RegularExpression Id. */
  int EXP = 74;
  /** RegularExpression Id. */
  int NOR = 75;
  /** RegularExpression Id. */
  int POI = 76;
  /** RegularExpression Id. */
  int UNI = 77;
  /** RegularExpression Id. */
  int BETA = 78;
  /** RegularExpression Id. */
  int BINOM = 79;
  /** RegularExpression Id. */
  int CHISQR = 80;
  /** RegularExpression Id. */
  int GAMMA = 81;
  /** RegularExpression Id. */
  int CONST = 82;
  /** RegularExpression Id. */
  int RESPT = 83;
  /** RegularExpression Id. */
  int WAITT = 84;
  /** RegularExpression Id. */
  int UTIL = 85;
  /** RegularExpression Id. */
  int QLEN = 86;
  /** RegularExpression Id. */
  int AVAIL = 87;
  /** RegularExpression Id. */
  int POWER = 88;
  /** RegularExpression Id. */
  int EPERR = 89;
  /** RegularExpression Id. */
  int PDP = 90;
  /** RegularExpression Id. */
  int PEFF = 91;
  /** RegularExpression Id. */
  int TPUT = 92;
  /** RegularExpression Id. */
  int BPUT = 93;
  /** RegularExpression Id. */
  int GPUT = 94;
  /** RegularExpression Id. */
  int BUFFTIMEOUT = 95;
  /** RegularExpression Id. */
  int DROPRATE = 96;
  /** RegularExpression Id. */
  int AVGSERVT = 97;
  /** RegularExpression Id. */
  int QPARMS = 98;
  /** RegularExpression Id. */
  int BOTTLENECK = 99;
  /** RegularExpression Id. */
  int BLOCKPROB = 100;
  /** RegularExpression Id. */
  int PRINTCFG = 101;
  /** RegularExpression Id. */
  int ARATE = 102;
  /** RegularExpression Id. */
  int ANALYSE = 103;
  /** RegularExpression Id. */
  int INTERVAL = 104;
  /** RegularExpression Id. */
  int FREQ = 105;
  /** RegularExpression Id. */
  int FOREACH = 106;
  /** RegularExpression Id. */
  int FOR = 107;
  /** RegularExpression Id. */
  int TO = 108;
  /** RegularExpression Id. */
  int INCR = 109;
  /** RegularExpression Id. */
  int DECR = 110;
  /** RegularExpression Id. */
  int SET = 111;
  /** RegularExpression Id. */
  int PRINT = 112;
  /** RegularExpression Id. */
  int IN = 113;
  /** RegularExpression Id. */
  int AND = 114;
  /** RegularExpression Id. */
  int IF = 115;
  /** RegularExpression Id. */
  int THEN = 116;
  /** RegularExpression Id. */
  int ELSE = 117;
  /** RegularExpression Id. */
  int WHILE = 118;
  /** RegularExpression Id. */
  int BREAK = 119;
  /** RegularExpression Id. */
  int BRANCH = 120;
  /** RegularExpression Id. */
  int MODELPARAMS = 121;
  /** RegularExpression Id. */
  int LOADPARAMS = 122;
  /** RegularExpression Id. */
  int ANALYTICAL = 123;
  /** RegularExpression Id. */
  int SIMULATION = 124;
  /** RegularExpression Id. */
  int THINKTIME = 125;
  /** RegularExpression Id. */
  int TIMEOUT = 126;
  /** RegularExpression Id. */
  int RETRYPROB = 127;
  /** RegularExpression Id. */
  int OPEN = 128;
  /** RegularExpression Id. */
  int TYPE = 129;
  /** RegularExpression Id. */
  int METHOD = 130;
  /** RegularExpression Id. */
  int CLOSED = 131;
  /** RegularExpression Id. */
  int NOOFUSERS = 132;
  /** RegularExpression Id. */
  int NOOFREQUESTS = 133;
  /** RegularExpression Id. */
  int SIMENDTIME = 134;
  /** RegularExpression Id. */
  int CONFINT = 135;
  /** RegularExpression Id. */
  int REPLICATIONNO = 136;
  /** RegularExpression Id. */
  int STARTUPSAMPLENO = 137;
  /** RegularExpression Id. */
  int OUTPUT = 138;
  /** RegularExpression Id. */
  int COOLDOWNSAMPLENO = 139;
  /** RegularExpression Id. */
  int ENABLE = 140;
  /** RegularExpression Id. */
  int DISABLE = 141;
  /** RegularExpression Id. */
  int MAXRETRY = 142;
  /** RegularExpression Id. */
  int WORKLOAD = 143;
  /** RegularExpression Id. */
  int CYCLIC = 144;
  /** RegularExpression Id. */
  int VIRTUALIZATION = 145;
  /** RegularExpression Id. */
  int ON = 146;
  /** RegularExpression Id. */
  int OFF = 147;
  /** RegularExpression Id. */
  int MIGRATIONPOLICY = 148;
  /** RegularExpression Id. */
  int TIMEBASED = 149;
  /** RegularExpression Id. */
  int AFTER = 150;
  /** RegularExpression Id. */
  int VMNAME = 151;
  /** RegularExpression Id. */
  int DESTPMNAME = 152;
  /** RegularExpression Id. */
  int CONSTANT = 153;
  /** RegularExpression Id. */
  int NUMBER = 154;
  /** RegularExpression Id. */
  int STRING_LITERAL = 155;
  /** RegularExpression Id. */
  int FILENAME = 156;
  /** RegularExpression Id. */
  int IDENTIFIER = 157;
  /** RegularExpression Id. */
  int DIGITS = 158;
  /** RegularExpression Id. */
  int LETTER = 159;
  /** RegularExpression Id. */
  int DIGIT = 160;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"scenario\"",
    "\"end\"",
    "\"variable\"",
    "\"pdevice\"",
    "\"devicecategory\"",
    "\"vdevice\"",
    "\"cpu\"",
    "\"noncpu\"",
    "\"vcpu\"",
    "\"vstorage\"",
    "\"ps\"",
    "\"fcfs\"",
    "\"lcfs\"",
    "\"xcs\"",
    "\"deploy\"",
    "\"undeploy\"",
    "\"physicalmachine\"",
    "\"virtualmachine\"",
    "\"server\"",
    "\"count\"",
    "\"prob\"",
    "\"sync\"",
    "\"servt\"",
    "\"at\"",
    "\"thread\"",
    "\"task\"",
    "\"buffer\"",
    "\"basespeed\"",
    "\"softres\"",
    "\"schedp\"",
    "\"speedup\"",
    "\"true\"",
    "\"false\"",
    "\"ram\"",
    "\"staticsize\"",
    "\"size\"",
    "\"warnings\"",
    "\"power_managed\"",
    "\"governor\"",
    "\"conservative\"",
    "\"ondemand\"",
    "\"performance\"",
    "\"powersave\"",
    "\"userspace\"",
    "\"powermanagement\"",
    "\"speed_levels\"",
    "\"power_consumed\"",
    "\"idlepower\"",
    "\"setspeed_level_index\"",
    "\"probe_interval\"",
    "\"probe_interval_down_factor\"",
    "\"governor_up_threshold\"",
    "\"governor_down_threshold\"",
    "\"lan\"",
    "\"link\"",
    "\"prop\"",
    "\"trans\"",
    "\"headersize\"",
    "\"bytes\"",
    "\"ms\"",
    "\"us\"",
    "\"ns\"",
    "\"Kbps\"",
    "\"bps\"",
    "\"Mbps\"",
    "\"Gbps\"",
    "\"mtu\"",
    "\"exp\"",
    "\"nor\"",
    "\"poi\"",
    "\"uni\"",
    "\"beta\"",
    "\"binom\"",
    "\"chisqr\"",
    "\"gamma\"",
    "\"const\"",
    "\"respt\"",
    "\"waitt\"",
    "\"util\"",
    "\"qlen\"",
    "\"avail\"",
    "\"power\"",
    "\"eperr\"",
    "\"pdp\"",
    "\"peff\"",
    "\"tput\"",
    "\"bput\"",
    "\"gput\"",
    "\"buffTimeout\"",
    "\"droprate\"",
    "\"avgservt\"",
    "\"qparms\"",
    "\"bottleneck\"",
    "\"blockprob\"",
    "\"printcfg\"",
    "\"arate\"",
    "\"analyse\"",
    "\"interval\"",
    "\"freq\"",
    "\"foreach\"",
    "\"for\"",
    "\"to\"",
    "\"incr\"",
    "\"decr\"",
    "\"set\"",
    "\"print\"",
    "\"in\"",
    "\"and\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"break\"",
    "\"branch\"",
    "\"modelparams\"",
    "\"loadparams\"",
    "\"analytical\"",
    "\"simulation\"",
    "\"thinktime\"",
    "\"timeout\"",
    "\"retryProb\"",
    "\"open\"",
    "\"type\"",
    "\"method\"",
    "\"closed\"",
    "\"noofusers\"",
    "\"noofrequests\"",
    "\"simendtime\"",
    "\"confint\"",
    "\"replicationno\"",
    "\"startupsampleno\"",
    "\"output\"",
    "\"cooldownsampleno\"",
    "\"enable\"",
    "\"disable\"",
    "\"maxretry\"",
    "\"workload\"",
    "\"cyclic\"",
    "\"virtualization\"",
    "\"ON\"",
    "\"OFF\"",
    "\"migrationpolicy\"",
    "\"timebased\"",
    "\"after\"",
    "\"vmname\"",
    "\"destpmname\"",
    "\"constant\"",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "<FILENAME>",
    "<IDENTIFIER>",
    "<DIGITS>",
    "<LETTER>",
    "<DIGIT>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"+\"",
    "\":\"",
    "\"()\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
