/* Generated By:JavaCC: Do not edit this line. PerfParserTokenManager.java */
package perfcenter.parser;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.*;
import perfcenter.baseclass.*;
import perfcenter.baseclass.enums.*;
import perfcenter.baseclass.exception.*;

/** Token Manager. */
public class PerfParserTokenManager implements PerfParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active2 & 0x10000000000000L) != 0L)
            return 21;
         if ((active0 & 0xffffffffffffff80L) != 0L || (active1 & 0xffffffffffffffffL) != 0L || (active2 & 0x3ffffffL) != 0L)
         {
            jjmatchedKind = 157;
            return 42;
         }
         return -1;
      case 1:
         if ((active0 & 0x4000040020000L) != 0L || (active1 & 0xa31000000001cL) != 0L || (active2 & 0x40000L) != 0L)
            return 42;
         if ((active0 & 0xfffbffffbffdff80L) != 0L || (active1 & 0xfff5ceffffffffe3L) != 0L || (active2 & 0x3fbffffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 1;
            }
            return 42;
         }
         return -1;
      case 2:
         if ((active0 & 0x1080010000102100L) != 0L || (active1 & 0x48c0004003e40L) != 0L || (active2 & 0x80000L) != 0L)
            return 42;
         if ((active0 & 0xef7ffeffbfedde80L) != 0L || (active1 & 0xfff163fffbffc1a3L) != 0L || (active2 & 0x3f3ffffL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 2;
            }
            return 42;
         }
         return -1;
      case 3:
         if ((active0 & 0x63000441180c8000L) != 0L || (active1 & 0x306200786041a0L) != 0L || (active2 & 0x3L) != 0L)
            return 42;
         if ((active0 & 0x8cfffabea7e15e80L) != 0L || (active1 & 0xffc105ff839f8003L) != 0L || (active2 & 0x3f3fffcL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 3;
            }
            return 42;
         }
         return -1;
      case 4:
         if ((active0 & 0x802a108024000000L) != 0L || (active1 & 0xc10060039e8002L) != 0L || (active2 & 0x2400000L) != 0L)
            return 42;
         if ((active0 & 0xfd5ea3e83e15e80L) != 0L || (active1 & 0xff00059f80010001L) != 0L || (active2 & 0x1b3fffcL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 4;
            }
            return 42;
         }
         return -1;
      case 5:
         if ((active0 & 0x1282204000L) != 0L || (active1 & 0x100000400010000L) != 0L || (active2 & 0x81140cL) != 0L)
            return 42;
         if ((active0 & 0xffffa2c01c11e80L) != 0L || (active1 & 0xfe0005bb80000001L) != 0L || (active2 & 0x332ebf0L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 5;
            return 42;
         }
         return -1;
      case 6:
         if ((active0 & 0x2800001400L) != 0L || (active1 & 0x4000048000000000L) != 0L || (active2 & 0x2080L) != 0L)
            return 42;
         if ((active0 & 0xffffa0401c10a80L) != 0L || (active1 & 0xbe00013b80000001L) != 0L || (active2 & 0x332cb70L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 6;
            return 42;
         }
         return -1;
      case 7:
         if ((active0 & 0xc00a80000410280L) != 0L || (active1 & 0x12300000000L) != 0L || (active2 & 0x200c000L) != 0L)
            return 42;
         if ((active0 & 0x3ff520401800800L) != 0L || (active1 & 0xbe00001880000001L) != 0L || (active2 & 0x1320b70L) != 0L)
         {
            if (jjmatchedPos != 7)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 7;
            }
            return 42;
         }
         return -1;
      case 8:
         if ((active0 & 0x46000400000000L) != 0L || (active1 & 0xa000001000000000L) != 0L || (active2 & 0x200010L) != 0L)
            return 42;
         if ((active0 & 0xfb9520001800800L) != 0L || (active1 & 0x1e00000880000001L) != 0L || (active2 & 0x1120b60L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 8;
            return 42;
         }
         return -1;
      case 9:
         if ((active0 & 0x20000000000L) != 0L || (active1 & 0x1c00000800000001L) != 0L || (active2 & 0x1000040L) != 0L)
            return 42;
         if ((active0 & 0xfb9500001800800L) != 0L || (active1 & 0x200000080000000L) != 0L || (active2 & 0x120b20L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 9;
            return 42;
         }
         return -1;
      case 10:
         if ((active0 & 0x1000000000000L) != 0L || (active1 & 0x200000080000000L) != 0L)
            return 42;
         if ((active0 & 0xfb8500001800800L) != 0L || (active2 & 0x120b20L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 10;
            return 42;
         }
         return -1;
      case 11:
         if ((active0 & 0x10400000000000L) != 0L || (active2 & 0x20L) != 0L)
            return 42;
         if ((active0 & 0xfa8100001800800L) != 0L || (active2 & 0x120b00L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 11;
            return 42;
         }
         return -1;
      case 12:
         if ((active0 & 0x100000000000L) != 0L || (active2 & 0x100L) != 0L)
            return 42;
         if ((active0 & 0xfa8000001800800L) != 0L || (active2 & 0x120a00L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 12;
            return 42;
         }
         return -1;
      case 13:
         if ((active0 & 0x320000001000800L) != 0L || (active2 & 0x20000L) != 0L)
            return 42;
         if ((active0 & 0xc88000000800000L) != 0L || (active2 & 0x100a00L) != 0L)
         {
            if (jjmatchedPos != 13)
            {
               jjmatchedKind = 157;
               jjmatchedPos = 13;
            }
            return 42;
         }
         return -1;
      case 14:
         if ((active0 & 0x8000000800000L) != 0L || (active2 & 0x100200L) != 0L)
            return 42;
         if ((active0 & 0xe80000000000000L) != 0L || (active2 & 0x800L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 14;
            return 42;
         }
         return -1;
      case 15:
         if ((active2 & 0x800L) != 0L)
            return 42;
         if ((active0 & 0xe80000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 15;
            return 42;
         }
         return -1;
      case 16:
         if ((active0 & 0xe80000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 16;
            return 42;
         }
         return -1;
      case 17:
         if ((active0 & 0xe80000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 17;
            return 42;
         }
         return -1;
      case 18:
         if ((active0 & 0xe80000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 18;
            return 42;
         }
         return -1;
      case 19:
         if ((active0 & 0x80000000000000L) != 0L)
            return 42;
         if ((active0 & 0xe00000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 19;
            return 42;
         }
         return -1;
      case 20:
         if ((active0 & 0x400000000000000L) != 0L)
            return 42;
         if ((active0 & 0xa00000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 20;
            return 42;
         }
         return -1;
      case 21:
         if ((active0 & 0xa00000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 21;
            return 42;
         }
         return -1;
      case 22:
         if ((active0 & 0x800000000000000L) != 0L)
            return 42;
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 22;
            return 42;
         }
         return -1;
      case 23:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 23;
            return 42;
         }
         return -1;
      case 24:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 157;
            jjmatchedPos = 24;
            return 42;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x200000000000L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x80000000000L);
      case 40:
         jjmatchedKind = 163;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10000000000L);
      case 41:
         return jjStopAtPos(0, 164);
      case 42:
         return jjStopAtPos(0, 179);
      case 43:
         return jjStopAtPos(0, 166);
      case 44:
         return jjStopAtPos(0, 165);
      case 45:
         return jjStopAtPos(0, 178);
      case 47:
         return jjStartNfaWithStates_0(0, 180, 21);
      case 58:
         return jjStopAtPos(0, 167);
      case 60:
         jjmatchedKind = 174;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1000000000000L);
      case 61:
         jjmatchedKind = 169;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x100000000000L);
      case 62:
         jjmatchedKind = 175;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x2000000000000L);
      case 91:
         return jjStopAtPos(0, 161);
      case 93:
         return jjStopAtPos(0, 162);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x80400c200800000L, 0x400000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x600000000L, 0x1800018a000c042L, 0x0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x400004002000L, 0x50000L, 0x2010888L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x200800L, 0x400100000000L, 0x1002000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x100L, 0x20000002000400L, 0x1000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8000040000L, 0xe0000000000L, 0x0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0xc00200000000000L, 0x40020100L, 0x0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L, 0x0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0xa210000000000L, 0x0L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20L, 0x0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x3000000000080000L, 0x400000000000000L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000284L, 0x104004L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x810L, 0x30L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L, 0xc0401L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x432b100008820400L, 0x100200d001000L, 0x0L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400400000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x8000000000080000L, 0x100L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x90063832000080L, 0x1000800000000000L, 0x240L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x8000004180000000L, 0x6010100010000000L, 0x200002L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x4000000400000L, 0x202008L, 0x0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x1019200L, 0x0L, 0x820000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x80000000000L, 0x40000000100000L, 0x8000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa1_0(0x100000L, 0x0L, 0x0L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x40000000000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active2 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 171);
         break;
      case 41:
         if ((active2 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 168);
         break;
      case 61:
         if ((active2 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 172);
         else if ((active2 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 173);
         else if ((active2 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 176);
         else if ((active2 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 177);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000098500000200L, active1, 0x120000L, active2, 0x4000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1a0L, active2, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x10001c8080L, active1, 0L, active2, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000001400L, active1, 0x4000000L, active2, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x81000022200800L, active1, 0x8000c00008084001L, active2, 0x1000104L);
      case 70:
      case 102:
         if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 115, 42);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x480000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x80800000L, active1, 0x2050000000010000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000040001000000L, active1, 0x5000000000008000L, active2, 0x322040L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20001000400000L, active2, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x800000L);
      case 78:
      case 110:
         if ((active1 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 113;
            jjmatchedPos = 1;
         }
         else if ((active2 & 0x40000L) != 0L)
         {
            jjmatchedKind = 146;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x800000400100L, active1, 0x804218000002000L, active2, 0x1000L);
      case 79:
      case 111:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 108, 42);
         return jjMoveStringLiteralDfa2_0(active0, 0xc2a700804004000L, active1, 0x6000c0801041800L, active2, 0x20088b0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x10002000002000L, active1, 0x472000040L, active2, 0x1L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0xc300004008000000L, active1, 0x181026100000000L, active2, 0L);
      case 83:
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 42);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(1, 66, 42);
         else if ((active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(1, 68, 42);
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000010000L, active1, 0L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(1, 30, 42);
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L, active1, 0x200200L, active2, 0x200L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L, active1, 0x80000000L, active2, 0x400L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200800000L, active2, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x400L, active2, 0L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L, active1, 0x2L, active2, 0x10002L);
      case 124:
         if ((active2 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 170);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000020000000000L, active1, 0xd0000c400800001L, active2, 0x1200L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x600000000000L, active2, 0x10000L);
      case 68:
      case 100:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 8, 42);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 114, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000400000L, active1, 0x200000000000000L, active2, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x14002000001480L, active1, 0x90020002400000L, active2, 0x1L);
      case 70:
      case 102:
         if ((active2 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 147, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0xa000c0000L, active1, 0x88000000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x200000000L, active2, 0x100000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L, active1, 0L, active2, 0L);
      case 73:
      case 105:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(2, 76, 42);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(2, 77, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2041002000310000L, active2, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x40008000000000L, active1, 0L, active2, 0L);
      case 77:
      case 109:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 40, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x5000000000020000L, active2, 0x200040L);
      case 78:
      case 110:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 60, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000400010004000L, active1, 0x48000L, active2, 0x2800080L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4300000008000000L, active1, 0x1100000000L, active2, 0x838L);
      case 80:
      case 112:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(2, 74, 42);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(2, 90, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0x208000L, active1, 0x1a0L, active2, 0x102L);
      case 82:
      case 114:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 75, 42);
         else if ((active1 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 107;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10800a3000200L, active1, 0x40000000000L, active2, 0x28000L);
      case 83:
      case 115:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(2, 20, 42);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(2, 70, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0x500000000L, active1, 0x20000000080000L, active2, 0x1002000L);
      case 84:
      case 116:
         if ((active1 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 111;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000010000L, active1, 0x8000010800004002L, active2, 0x400404L);
      case 85:
      case 117:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(2, 13, 42);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 42);
         return jjMoveStringLiteralDfa3_0(active0, 0x4004000000L, active1, 0x70000000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0xc00200000000800L, active1, 0L, active2, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x2a100000000000L, active1, 0x1000000L, active2, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x4000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(3, 78, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x80000000000000L, active2, 0x802000L);
      case 66:
      case 98:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x300000000000000L, active1, 0L, active2, 0x1000L);
      case 67:
      case 99:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L, active1, 0x1000000000L, active2, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400000000000001L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 38, 42);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 42);
         else if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 117, 42);
         else if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 129, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0xc7ab03480400000L, active1, 0x4200050001000002L, active2, 0x600040L);
      case 70:
      case 102:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 91, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000200000000L, active1, 0x80000000L, active2, 0xb0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0xa00L, active1, 0x800000L, active2, 0L);
      case 75:
      case 107:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 42);
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 61, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x8000L);
      case 76:
      case 108:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 85, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0x840008000000000L, active2, 0x10900L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20000L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 86, 42);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 116, 42);
         else if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 128, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000080004000080L, active1, 0x2101002000000000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L, active1, 0x8000L, active2, 0L);
      case 80:
      case 112:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 62, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100080000L, active2, 0x400L);
      case 81:
      case 113:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 105, 42);
         break;
      case 82:
      case 114:
         if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 109, 42);
         else if ((active1 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 110, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L, active1, 0x8000000402000000L, active2, 0x104200L);
      case 83:
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 42);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 42);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 69, 42);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 42);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x80408000800000L, active1, 0x200050000L, active2, 0x2000008L);
      case 84:
      case 116:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 92, 42);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 93, 42);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 94, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0x20801000000L, active1, 0x4800100000L, active2, 0x1020000L);
      case 85:
      case 117:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 42);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000000000000000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x22001400L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 81, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000280L, active1, 0x40000000000L, active2, 0x100000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x202000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L, active1, 0x100000000000000L, active2, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x10003000000000L, active1, 0L, active2, 0x800L);
      case 69:
      case 101:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 42);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 102, 42);
         else if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 118, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0x300400202000000L, active1, 0x200000001L, active2, 0x4008L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0xa0000801400L, active1, 0L, active2, 0x10180L);
      case 75:
      case 107:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 119, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2000001000000000L, active2, 0L);
      case 76:
      case 108:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 87, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1200000800000000L, active2, 0x9000L);
      case 77:
      case 109:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 79, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L, active1, 0x400000000L, active2, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x40L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000200000L, active1, 0x4000000000000000L, active2, 0x4L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000000404000L, active1, 0x400000000000000L, active2, 0x1000000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10000L, active2, 0L);
      case 82:
      case 114:
         if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 89, 42);
         else if ((active2 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(4, 150, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0xc2a300800010000L, active1, 0x10100000000L, active2, 0x20L);
      case 83:
      case 115:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 63, 42);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(4, 65, 42);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000400000000L, active1, 0L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 42);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 42);
         else if ((active1 & 0x40000L) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 83, 42);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 84, 42);
         else if ((active1 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 112;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2080000000L, active2, 0x2000200L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L, active1, 0L, active2, 0x20410L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8800008000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x330100000000000L, active1, 0L, active2, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x800001010000L, active1, 0x1400000100000000L, active2, 0x2220000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x200L, active1, 0L, active2, 0L);
      case 67:
      case 99:
         if ((active2 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 144, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000801400L, active1, 0x42000000000L, active2, 0x100L);
      case 68:
      case 100:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 42);
         else if ((active2 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 130, 42);
         else if ((active2 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(5, 131, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x40L);
      case 69:
      case 101:
         if ((active2 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 140, 42);
         else if ((active2 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 151, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000800000800L, active1, 0x800000000L, active2, 0x20L);
      case 72:
      case 104:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 120, 42);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x80000000L, active2, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L, active1, 0L, active2, 0x2000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0L, active2, 0x1000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xc00280000000000L, active1, 0L, active2, 0x80L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000000L, active1, 0L, active2, 0x8800L);
      case 80:
      case 112:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 36, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000400000000L, active1, 0x8200001000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 42);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 42);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x1400000000080L, active1, 0x200000001L, active2, 0L);
      case 83:
      case 115:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 98, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L, active1, 0x8000000000L, active2, 0x10L);
      case 84:
      case 116:
         if ((active2 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 138, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2800000000000000L, active2, 0x104000L);
      case 85:
      case 117:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 42);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L, active1, 0x4000000000000000L, active2, 0x200L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000000000L, active2, 0L);
      case 89:
      case 121:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 21, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0xe000000800000L, active1, 0x200010000000000L, active2, 0x8100L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000800L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(6, 10, 42);
         else if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 42);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 103, 42);
         else if ((active2 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 141, 42);
         return jjMoveStringLiteralDfa7_0(active0, 0x80000400000000L, active1, 0L, active2, 0x10L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000000000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000010000L, active1, 0L, active2, 0L);
      case 72:
      case 104:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 106, 42);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x300000000000080L, active1, 0x2800000000000000L, active2, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000001000200L, active1, 0L, active2, 0x20000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x1100000000000L, active1, 0x80000000L, active2, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L, active1, 0x800000000L, active2, 0x3000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0xc00200000400000L, active1, 0L, active2, 0L);
      case 80:
      case 112:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 42);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x200L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8400001000000000L, active2, 0x4000L);
      case 83:
      case 115:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 35, 42);
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L, active1, 0x1L, active2, 0x200000L);
      case 84:
      case 116:
         if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 126, 42);
         else if ((active2 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(6, 135, 42);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000000100000000L, active2, 0x40L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L, active1, 0x200000000L, active2, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000000L, active1, 0L, active2, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x1500000000800L, active1, 0x400000000000000L, active2, 0x1000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000L, active1, 0x800000000000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 47, 42);
         else if ((active2 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 143, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000000L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(7, 9, 42);
         else if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 42);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 96, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0x50000400000000L, active1, 0x880000000L, active2, 0x200000L);
      case 71:
      case 103:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 101, 42);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L, active1, 0x1000000000000001L, active2, 0x20040L);
      case 76:
      case 108:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 104, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000L, active1, 0x2000000000000000L, active2, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x308000000000000L, active1, 0L, active2, 0x800L);
      case 79:
      case 111:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(7, 7, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000000L, active1, 0x8000001000000000L, active2, 0x100000L);
      case 82:
      case 114:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0xc00000000000000L, active1, 0x200000000000000L, active2, 0x10L);
      case 83:
      case 115:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 43, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x200L);
      case 84:
      case 116:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(7, 97, 42);
         else if ((active2 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 153, 42);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x100L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L, active1, 0L, active2, 0L);
      case 89:
      case 121:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(7, 22, 42);
         else if ((active2 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(7, 142, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0xc80000000000000L, active1, 0L, active2, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000001000000L, active1, 0xa00000000000000L, active2, 0x200L);
      case 66:
      case 98:
         if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 100, 42);
         else if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 127, 42);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x800000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(8, 34, 42);
         else if ((active2 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(8, 149, 42);
         break;
      case 69:
      case 101:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 49, 42);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 50, 42);
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 125, 42);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0L, active2, 0x20L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0L, active2, 0x100L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L, active1, 0x400000000000000L, active2, 0x1000040L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x21100000000000L, active1, 0L, active2, 0x100000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x1000000080000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 54, 42);
         break;
      case 83:
      case 115:
         if ((active2 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(8, 132, 42);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0L, active2, 0x800L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x300400000000800L, active1, 0L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000000L, active1, 0L, active2, 0L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L, active1, 0x1L, active2, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, active2);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000800000L, active1, 0L, active2, 0x20800L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000001000000L, active1, 0L, active2, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000000000L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 41, 42);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(9, 64, 42);
         else if ((active2 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(9, 134, 42);
         else if ((active2 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(9, 152, 42);
         return jjMoveStringLiteralDfa10_0(active0, 0x310000000000800L, active1, 0L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L, active1, 0L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 75:
      case 107:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(9, 99, 42);
         break;
      case 76:
      case 108:
         if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 123, 42);
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000000L, active1, 0L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x200000000000000L, active2, 0x200L);
      case 78:
      case 110:
         if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 124, 42);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0L, active2, 0x100L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0L, active2, 0x100000L);
      case 83:
      case 115:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 122, 42);
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000000L, active1, 0L, active2, 0x20L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000000L, active1, 0x80000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(8, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1, active2);
      return 10;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 48, 42);
         return jjMoveStringLiteralDfa11_0(active0, 0x88000000000000L, active1, 0L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000000800L, active1, 0L, active2, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000L, active1, 0L, active2, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000000000L, active1, 0L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0L, active2, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0L, active2, 0x100L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000000000000L, active1, 0L, active2, 0x100000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000000000L, active1, 0L, active2, 0x200L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x300000000000000L, active1, 0L, active2, 0L);
      case 83:
      case 115:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 121, 42);
         break;
      case 84:
      case 116:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(10, 95, 42);
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0L, active2, 0x20020L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000000L, active1, 0L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(9, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L, active2);
      return 11;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 46, 42);
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000000L, active2, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L, active2, 0x20000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active2, 0x100200L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0x28000000000000L, active2, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active2, 0x100L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x800L, active2, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active2, 0x800L);
      case 83:
      case 115:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 52, 42);
         else if ((active2 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(11, 133, 42);
         break;
      case 86:
      case 118:
         return jjMoveStringLiteralDfa12_0(active0, 0x380000000000000L, active2, 0L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L, active2);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old2, long active2)
{
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(10, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L, active2);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x300000000000000L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 44, 42);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0xa8000000000000L, active2, 0x200L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L, active2, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active2, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000001000000L, active2, 0L);
      case 79:
      case 111:
         if ((active2 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(12, 136, 42);
         return jjMoveStringLiteralDfa13_0(active0, 0L, active2, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x800L, active2, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L, active2);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old2, long active2)
{
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(11, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L, active2);
      return 13;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa14_0(active0, 0x800000000000000L, active2, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active2, 0x100000L);
      case 68:
      case 100:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 53, 42);
         break;
      case 69:
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(13, 24, 42);
         return jjMoveStringLiteralDfa14_0(active0, 0L, active2, 0x800L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa14_0(active0, 0x400000000000000L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 13;
         }
         return jjMoveStringLiteralDfa14_0(active0, 0x280000000000000L, active2, 0L);
      case 78:
      case 110:
         if ((active2 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(13, 145, 42);
         return jjMoveStringLiteralDfa14_0(active0, 0x8000000800000L, active2, 0x200L);
      case 89:
      case 121:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(13, 11, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L, active2);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0, long old2, long active2)
{
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(12, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L, active2);
      return 14;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa15_0(active0, 0x280000000000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(14, 23, 42);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active2, 0x800L);
      case 79:
      case 111:
         if ((active2 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(14, 137, 42);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000000000000L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 51, 42);
         return jjMoveStringLiteralDfa15_0(active0, 0x800000000000000L, active2, 0L);
      case 89:
      case 121:
         if ((active2 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(14, 148, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L, active2);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0, long old2, long active2)
{
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(13, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L, active2);
      return 15;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa16_0(active0, 0x200000000000000L, active2, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000000000000L, active2, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa16_0(active0, 0x800000000000000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x80000000000000L, active2, 0L);
      case 79:
      case 111:
         if ((active2 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(15, 139, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L, active2);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0, long old2, long active2)
{
   if (((active0 &= old0) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(14, old0, 0L, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa17_0(active0, 0x80000000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x200000000000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa17_0(active0, 0x800000000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0, 0L, 0L);
      return 17;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa18_0(active0, 0x80000000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa18_0(active0, 0x800000000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa18_0(active0, 0x400000000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa18_0(active0, 0x200000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0, 0L, 0L);
      return 18;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa19_0(active0, 0x80000000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa19_0(active0, 0x200000000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa19_0(active0, 0x400000000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa19_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0, 0L, 0L);
      return 19;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa20_0(active0, 0x200000000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa20_0(active0, 0x800000000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa20_0(active0, 0x400000000000000L);
      case 88:
      case 120:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(19, 55, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0, 0L, 0L);
      return 20;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(20, 58, 42);
         break;
      case 70:
      case 102:
         return jjMoveStringLiteralDfa21_0(active0, 0x200000000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa21_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0, 0L, 0L);
      return 21;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa22_0(active0, 0x200000000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa22_0(active0, 0x800000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0, 0L, 0L);
      return 22;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa23_0(active0, 0x200000000000000L);
      case 68:
      case 100:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(22, 59, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(21, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa23_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(21, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(22, active0, 0L, 0L);
      return 23;
   }
   switch(curChar)
   {
      case 84:
      case 116:
         return jjMoveStringLiteralDfa24_0(active0, 0x200000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(22, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa24_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(22, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(23, active0, 0L, 0L);
      return 24;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa25_0(active0, 0x200000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(23, active0, 0L, 0L);
}
static private int jjMoveStringLiteralDfa25_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(23, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(24, active0, 0L, 0L);
      return 25;
   }
   switch(curChar)
   {
      case 82:
      case 114:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(25, 57, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(24, active0, 0L, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 42;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 21:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(13, 14);
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(27, 28);
                  if (curChar == 47)
                     jjCheckNAddStates(0, 2);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 154)
                        kind = 154;
                     jjCheckNAddStates(3, 8);
                  }
                  else if (curChar == 47)
                     jjAddStates(9, 10);
                  else if (curChar == 34)
                     jjCheckNAddStates(11, 13);
                  else if (curChar == 46)
                     jjCheckNAdd(1);
                  if (curChar == 47)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 157)
                        kind = 157;
                     jjCheckNAdd(33);
                  }
                  else if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 47)
                     jjCheckNAdd(14);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(17, 18);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 154)
                     kind = 154;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 34)
                     jjCheckNAddStates(11, 13);
                  break;
               case 3:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 5:
                  if ((0x8400002400L & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 6:
                  if (curChar == 34 && kind > 155)
                     kind = 155;
                  break;
               case 7:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(14, 17);
                  break;
               case 8:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 9:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(8);
                  break;
               case 11:
                  if (curChar == 10)
                     jjCheckNAddStates(11, 13);
                  break;
               case 12:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 16:
                  if (curChar == 47)
                     jjCheckNAdd(14);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(17, 18);
                  break;
               case 18:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 20:
                  if (curChar == 47)
                     jjAddStates(9, 10);
                  break;
               case 22:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 23:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 24:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 25:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 27:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 28:
                  if (curChar == 42)
                     jjCheckNAddStates(18, 20);
                  break;
               case 29:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(30, 28);
                  break;
               case 30:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(30, 28);
                  break;
               case 31:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 157)
                     kind = 157;
                  jjCheckNAdd(33);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 154)
                     kind = 154;
                  jjCheckNAddStates(3, 8);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 154)
                     kind = 154;
                  jjCheckNAdd(35);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 37:
                  if (curChar == 46)
                     jjCheckNAdd(38);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 154)
                     kind = 154;
                  jjCheckNAdd(38);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if (curChar == 46 && kind > 154)
                     kind = 154;
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 158)
                     kind = 158;
                  jjCheckNAdd(41);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 21:
               case 14:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(21, 24);
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 157)
                     kind = 157;
                  jjCheckNAddStates(25, 29);
                  break;
               case 42:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 157)
                        kind = 157;
                     jjCheckNAdd(33);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(17, 18);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 3:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 4:
                  if (curChar == 92)
                     jjAddStates(30, 33);
                  break;
               case 5:
                  if ((0x14404410144044L & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(17, 18);
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 156)
                     kind = 156;
                  jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 22:
                  jjAddStates(0, 2);
                  break;
               case 27:
                  jjCheckNAddTwoStates(27, 28);
                  break;
               case 29:
               case 30:
                  jjCheckNAddTwoStates(30, 28);
                  break;
               case 33:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 157)
                     kind = 157;
                  jjCheckNAdd(33);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(11, 13);
                  break;
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 2);
                  break;
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 29:
               case 30:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(30, 28);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 42 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   22, 23, 25, 35, 36, 37, 39, 40, 41, 21, 26, 3, 4, 6, 3, 4, 
   8, 6, 28, 29, 31, 15, 16, 17, 18, 15, 16, 17, 18, 33, 5, 7, 
   9, 12, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, "\133", "\135", "\50", "\51", "\54", 
"\53", "\72", "\50\51", "\75", "\174\174", "\46\46", "\75\75", "\41\75", "\74", 
"\76", "\74\75", "\76\75", "\55", "\52", "\57", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xffffffffffffffffL, 0x1ffffe7fffffffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[42];
static private final int[] jjstateSet = new int[84];
static protected char curChar;
/** Constructor. */
public PerfParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public PerfParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 42; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
